### ISSUE TITLE
Unable to annotate model when schema contains complex regex

### ISSUE THREAD

**Issue by mwpastore** [jeremyevans/sequel-annotate#5]
I'm generating a table with the following constraint:

```ruby
constraint(:valid_link) { (link =~ nil) | (link =~ URI.regexp(%w[http https])) }
```

The table looks fine (long regex omitted for brevity):

```
Check constraints:
    "valid_link" CHECK (link IS NULL OR link ~ '(?=(?-mix:http|https):)
```

However, when I attempt to annotate the corresponding model, I get the following error:

```
NoMethodError: undefined method `[]' for nil:NilClass
	from /Users/mwp/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sequel-annotate-1.1.0/lib/sequel/annotate.rb:132:in `block in _schema_comment_postgres'
	from /Users/mwp/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sequel-annotate-1.1.0/lib/sequel/annotate.rb:131:in `map'
	from /Users/mwp/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sequel-annotate-1.1.0/lib/sequel/annotate.rb:131:in `_schema_comment_postgres'
	from /Users/mwp/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sequel-annotate-1.1.0/lib/sequel/annotate.rb:67:in `schema_comment'
	from /Users/mwp/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sequel-annotate-1.1.0/lib/sequel/annotate.rb:46:in `annotate'
	from /Users/mwp/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sequel-annotate-1.1.0/lib/sequel/annotate.rb:15:in `block in annotate'
	from /Users/mwp/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sequel-annotate-1.1.0/lib/sequel/annotate.rb:13:in `each'
	from /Users/mwp/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sequel-annotate-1.1.0/lib/sequel/annotate.rb:13:in `annotate'
```

**Comment by jeremyevans** [comment]
Looks like it needs to be a multiline regexp.  I'll commit a patch shortly.
